# Generated by Django 3.1.3 on 2020-11-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название вклада')),
                ('percentage_rate', models.FloatField(verbose_name='Процентная ставка')),
                ('current_amount', models.FloatField(verbose_name='Текущая сумма')),
                ('percentage_accrual_date', models.DateField(verbose_name='Дата начисления процентов')),
                ('percentage_to_contribution', models.BooleanField(default=False, verbose_name='Проценты начисляются на вклад')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название транзакции')),
                ('ticket', models.TextField(verbose_name='Тикет')),
                ('price', models.FloatField(verbose_name='Цена транзакции')),
                ('data', models.DateField(verbose_name='Дата совершения транзакции')),
                ('active_type', models.PositiveIntegerField(verbose_name='Тип актива')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
